### ISSUE TITLE
Is it possible that we use suyu-emu/sirit to replace the original submodule yuzu-emu/sirit?

### ISSUE THREAD

**Issue by fusigi0930** [strato-emu/strato#259] opened 2024-03-08 08:20 UTC
the suyu-emu that is a fork from yuzu-emu in gitlab, but, it also has a fork in github
https://github.com/suyu-emu, it still under maintenance recently, maybe we can use it to instead of the sirit of yuzu-emu.

**Comment by Crytonics** [comment] 2024-03-08 11:28
Duplicate of #256

**Closed by Crytonics** 2024-03-08 11:28 UTC

**Comment by fusigi0930** [comment] 2024-03-14 01:21
yap, I had create a pull request for it before, but it is rejected.
#256

**Comment by steel101** [comment] 2024-03-16 13:26
> yap, I had done it and created a pull request for it before, but it is rejected #256

So I have many times with different links to. I gave them the original tha yuzu forked them self and they said no fuck them I made a lot of changes to keep the app going and make it better with all of yuzu code that they never added before it went down. I hope they get there asses out of there butt and start listing to people that want to help with project. Fuck them if they want to help
