### ISSUE TITLE
Add In Game Settings

### ISSUE THREAD

**Issue by Ishan0981** [strato-emu/strato#194] opened 2023-09-26 03:59 UTC
Add In Game Settings

**Comment by dima-xd** [comment] 2023-09-26 08:11
Isn't it a duplicate of https://github.com/strato-emu/strato/issues/178 ?

**Comment by Crytonics** [comment] 2023-09-26 09:26
> Isn't it a duplicate of #178 ?

Yea it is

**Comment by Crytonics** [comment] 2023-09-26 09:26
Duplicate of #178

**Closed by Crytonics** 2023-09-26 09:26 UTC
Labels: enhancement
