### ISSUE TITLE
In Built Keyboard Doesn't Work On Many Devices

### ISSUE THREAD

**Issue by Ishan0981** [strato-emu/strato#190] opened 2023-09-22 16:29 UTC
In Built Keyboard Doesn't Work On Many Devices
Device Name: OnePlus Nord 5G
Processor : 765G
GSMEREANA: https://m.gsmarena.com/oneplus_nord-10289.php
![Screenshot_20230922-215855](https://github.com/strato-emu/strato/assets/145665569/75b0d6c5-66a0-4405-b25e-cd8b8d09b227)

**Comment by dima-xd** [comment] 2023-09-22 18:20
It's not an official build of Skyline/Strato

**Comment by Crytonics** [comment] 2023-09-22 18:23
Duplicate of #185

**Comment by Crytonics** [comment] 2023-09-22 18:23
We don't provide support for unofficial builds.

**Closed by Crytonics** 2023-09-22 18:23 UTC
