### ISSUE TITLE
Freezing Crashing on Dimensity 8050

### ISSUE THREAD

**Issue by Ze3e3** [strato-emu/strato#57] opened 2023-07-01 06:33 UTC
While testing some of the games it either freezes at the start or freezes around half or later while playing

**Comment by lynxnb** [comment] 2023-08-09 11:12
The issue is too generic. We're aware that the emulator still experiences crashes and deadlocks, those will be fixed over time as the emulator is improved.

**Closed by lynxnb** 2023-08-09 11:12 UTC
Labels: bug
